### ISSUE TITLE
iqiyi 不能用了

### ISSUE THREAD

**Issue by PterX** [jc3213/soWatch#1]
看到你昨天更新了player，然后我也更新了，发现不能用了

**Comment by jc3213** [comment]
最近iQiyi官方频繁更新播放器，破解播放器若失效只能关闭在iQiyi上的功能（因为Filter效果不如ABP）。当然除了安装替换播放器的去广告扩展外，你可以参考下 https://greasyfork.org/zh-CN/scripts/8561-vipvideos-skipad

**Comment by jc3213** [comment]
Issue #7 已经解决了这个问题。
