### ISSUE TITLE
爱奇艺和优酷失效

### ISSUE THREAD

**Issue by waldens** [jc3213/soWatch#11]
测试网址：
<http://v.youku.com/v_show/id_XMTM5MDYyMjU2NA==.html?from=y1.7-1.1>
<http://www.iqiyi.com/v_19rrhkxmgc.html#curid=249870100_4295110d3a343b28941fc63f8fedb792>

环境：sowatchmk2-1.4.2-fx.xpi firefox v42.0 20151123测试

⓵ 本来用的uc脚本，发现失效后搜索到这里，改用sowatch
安装18号更新的v1.4.2后，已清理缓存，xml和替换播放器方法，都仍然不能播放。

⓶ 优酷爱奇艺，选择“恢复网站默认”，按设计逻辑，理应回到有广告播放状态吧？
但是没有，依然不能正常播放。

⓷ 另外禁用和移除sowatch、禁用uc脚本后，甚至进入安全模式禁用全部扩展
iqiyi仍然不能恢复正常带广告的播放
换profile则恢复正常
是否这两个工具其中之一，在卸载时，没有完全回退？没有恢复原状到安装前？

------

![](http://imagizer.imageshack.com/img911/6557/22hdrh.jpg)
![](http://imagizer.imageshack.com/img633/3363/hcvaog.jpg)

**Comment by jc3213** [comment]
这两个我这边测试都正常。单独测试soWatch并无法复现停用后依然生效的症状。

至于脚本的问题你应该找脚本的作者而不是我来反馈问题。我个人并不使用任何脚本。即使用也是暂时使用然后删除。我个人更推荐使用扩展。

至于优酷的话，之前跟我讨论过的人应该都知道现在的Filter规则并不完美，然而却也没有更好的方法。通过浏览器拦截能做到的比较有限（因为我们并不知道对方是怎么检测反广告的）。而Player这边，最好去卡饭论坛找15536900会比较好些，我并不维护，或提供任何破解播放器的下载。只是如果有人提供的话，我会添加他的hosts，仅此而已。

**Comment by waldens** [comment]
谢谢j兄！确实脚本和扩展都有效，是我本机问题。几个小时排查无果后，只好回退profile解决了…
（真是不解：卸载全部扩展，切安全模式，视频都仍然不能播…真不知哪儿引入的问题）
