### ISSUE TITLE
能否考虑增加17173这个网站，

### ISSUE THREAD

**Issue by 1608637229** [jc3213/soWatch#12]
17173 Adblock plus无法过滤，优酷的tvb这一类好像无法过滤，出现RTMP错误，

**Comment by jc3213** [comment]
17173曾经有一段时间由卡饭的 @catcat520 提供了一段时间的破解播放器，后来停止更新了。这里跟酷6一样是强制15秒。不管你怎么处理它都会黑15秒（播放器内置了15秒黑屏），因此不破解播放器无法完全的移除广告。并且该网站超过80%的资源基本都能从其他网站找到。而直播间更是大多数都直接引用的来自斗鱼跟战旗的。因此这个网站属于不会被支援之列。

另外优酷的tvb必须用 过滤广告请求 的功能。这是因为播放器的RTMP功能没得到解决，将来是否解决需要去卡饭 @15536900 。过滤功能会受Flash缓存影响，并且跟其他issue里提到的一样，隐私模式能减少 过滤模式下 出现45秒的几率。

**Comment by 1608637229** [comment]
好吧，谢谢您的解答
