### ISSUE TITLE
关于WebRequest.jsm API的相关问题

### ISSUE THREAD

**Issue by jc3213** [jc3213/soWatch#13]
本Issue的目的是将所有功能慢慢移植到新API上以保证在失去XPCOM接口后扩展仍能正常工作。关于WebRequest.jsm API后续相关移植工作的回馈，测试者的问题反馈（如果有的话）及将来的功能性修改等都将专门整理至本Issue。

目前移植功能已基本完成。然而却因为新WebRequest.jsm API不支持Suspend()，使得 不仅是Filter，包括Player功能都受到巨大的影响。由于工作模式的转变，原有大多数功能无法正常工作，只能移除。而目前新的Player方法无法直接从bitbucket调取托管的播放器，因此用户需要手动指定服务器。

具体细节可以参考下方表格，至于存在的潜在问题将在未来尝试修复。

最新测试版： https://github.com/jc3213/soWatch/releases/tag/2.0.0b3

进度：
Player 移植完成 （或不稳定）
Filter 移植完成
Referer 移植完成

修复：
Filter： 优酷 （尚未修复 临时禁用）
Filter： 搜狐 （尚未修复 临时禁用）

新增：
选项： 远程服务器 子项 523860169@coding.io

移除：
选项： 播放器自动更新
选项： 文件夹设置
选项： 本地文件夹
选项： 直连远程播放器
选项： 远程服务器 子项 15536900@bitbucket.org
功能： 调用本地播放器
功能： 播放器更新检查
功能： 过滤规则 —— 安全拦截
其他： 上述 功能/选项 相关代码

**Comment by aunsen** [comment]
药丸药丸

**Comment by jc3213** [comment]
已完成Referer的移植
https://github.com/jc3213/soWatch/releases/tag/1.7.0a3

**Comment by jc3213** [comment]
已完成Player的移植
https://github.com/jc3213/soWatch/releases/tag/1.7.0b1

大多数功能因此受限而不得不移除。用户需要手动指定服务器，bitbucket那边不能直接调用原因不知。
![about_addons](https://cloud.githubusercontent.com/assets/8744936/11917137/8c1e222e-a735-11e5-9a44-6671f6a192dd.png)

**Comment by jc3213** [comment]
感谢卡饭论坛523860169提供额外的服务器，目前播放器功能默认可用。
https://github.com/jc3213/soWatch/releases/tag/1.8.0b2

**Comment by jc3213** [comment]
@wenketel 不知道你那边方便不方便丢到贴吧找点小白鼠测试下这个版本。啧啧

**Comment by wenketel** [comment]
ok了，帖子[链接](http://tieba.baidu.com/p/4233550796)

**Comment by lsz7575** [comment]
感谢大神分享~~

**Comment by jc3213** [comment]
Simple Filter已经能实现除了伪造Referer外的所有功能了。如果未来添加修改 HTTP请求头 功能的话那么新版本的soWatch! mk2则没有必要出现了。此Issue到此为止。未来可能直接更新Simple Filter规则表，而不是做别的什么

**Comment by abbenyyyyyy** [comment]
OSX10.11.2下得火狐43.3谋智版，优酷没法播放（黑屏），爱奇艺提示"浏览器兼容或网络问题，请尝试用其他浏览器播放"，其余的正常跳过广告，谢谢！

**Comment by jc3213** [comment]
@abbenyyyyyy 爱奇艺我这边没任何问题。优酷的话可以参考其他issue提到的解决方法或者切换工作方法。

**Comment by aunsen** [comment]
药丸药丸

**Comment by greying** [comment]
soWatch依旧坚挺的！！！
