### ISSUE TITLE
是否需要开发支持低版本火狐的soWatch! 

### ISSUE THREAD

**Issue by jc3213** [jc3213/soWatch#14]
如Issue名，因为切换到Add-ons SDK后要求至少38.0a1以上才能正常工作，无法兼顾到一些低版本的用户。如果这些用户需要的话可以到本Issue进行投票，我会根据情况考虑是否重开soWatch!项目（目前源码已删，最新源码为AMO上保存的1.0.14）。

@wenketel

**Comment by wenketel** [comment]
有那个时间就做，忙的话就算了吧。::smile::

**Comment by jc3213** [comment]
@wenketel 时间是肯定有的，问题是如果用户群不多就算了。。我也就是看了下贴吧貌似有人还在用老版本。。帮我去贴吧做个调查吧。。看看最低版本大概是多少。。。28左右的话就可以保留播放器更新部分，不要工具栏按钮，不用Add-ons SDK，工作量也就等同soWatch! mk2的非SDK逆移植。这个的话可以在1.1.0ESR的基础上直接把新的代码套回来稍作修改就可以了。

**Comment by jc3213** [comment]
Firefox 38.0a1(若是新API版本则是41.0a1)以前，若是有需要可以访问下载 soWatch! https://github.com/jc3213/Misc/releases 不过由于soWatch! 用户较少，更新可能比较缓慢，基本可以看作soWatch! mk2的劣化版——没有播放器更新功能，没有工具栏按钮。

@wenketel 本Issue到此为止
