### ISSUE TITLE
sowatchmk2-2.0.0b3 会导致 Redirector 扩展的部分规则失效

### ISSUE THREAD

**Issue by AlwaysWithYou** [jc3213/soWatch#15]
sowatchmk2-2.0.0b3 会导致 Redirector 扩展部分规则失效，不过 sowatchmk2-1_0-fx 不会，两个版本都是从 release 里下载的。
失效的规则例子（通配符规则）： 
Redirect:  http://www.xxmer.com/go/?url=*
to:  $1
Example:  http://www.xxmer.com/go/?url=http://pan.baidu.com/s/1c0SQnJE → http://pan.baidu.com/s/1c0SQnJE
仍有效的规则例子（通配符规则）：
Redirect:  https://share.dmhy.org/*
to:  http://dmhy.dandanplay.com/$1
Example:  https://share.dmhy.org/cms/page/name/programme.html → http://dmhy.dandanplay.com/cms/page/name/programme.html
（重定向到的网址需要把 UA 改成 Chrome 的才可以正常访问）
貌似跟两个扩展的加载顺序有关——我禁用SoWatch，重启浏览器，然后再启用SoWatch，不会有失效的情况

**Comment by jc3213** [comment]
2.0.0b3已经停止更新了，因此不会再做相关维护。具体参考 #13
