### ISSUE TITLE
about iqiyi filter

### ISSUE THREAD

**Issue by jc3213** [jc3213/soWatch#7]
目前的filter拦截了由iqiyi am.swf生成的视频前广告的IP地址下的f4v视频后，am.swf会转而读取 http://data.video.qiyi.com 下面的hml文件，然后重新获取新的IP，进而又了如下测试：
1）如果同时拦截f4v跟hml，会因为无法正确获取广告，提示兼容问题。
2）如何只拦截f4v放行hml，广告文件被拦截，但15秒每广告的黑屏依然存在，加上重试次数等，甚至长于看广告。不过能正确过滤视频中跟视频末的广告。
3）拦截f4v,放行第一条hml，然后两者全部拦截。会黑屏大概30秒（两条广告的重试时间）然后正常播放视频。同2)
4) 放行第一个f4v,然后两者全部拦截。看一个广告16~17秒左右，然后同2)

如果参考4），你必须在广告开始播放后手动切换到Filter规则，或者启用下面的Adblock Plus规则
|http://*.*.*.*/videos/other/*$domain=iqiyi.com

多次测试基本4）的解决办法是最完美的了，只需要看一段广告（手慢可能要看更多），要么就是等待播放器破解。实在不知道那些软件是通过什么样的方式过滤掉广告的，至少看一眼规则也好。

PS:上述方法，亲测如果用sowatch实现的话整体效果还是不如ABP。这是个悲伤的故事，获取该试试别的思路来处理。

@GH-Kelo @ywzhaiqi @wenketel 不知道你们那有没方法实现上面的功能？

**Comment by jc3213** [comment]
根据commit 336a71a61cc5a2475da16ae7658c0871cfd79ddd ，实测大概还是有16~30秒左右的等待时间（第一个广告必看）。整体相对iqiyi超长时间（最低45，最高95）的广告，以及剧中广告，剧末广告来说要好多了吧？

希望有人能参与本次测试。

**Comment by cqhtyi** [comment]
测试结果如您所说，iqiyi第一个广告必看，后面的可以直接跳过，
第一个广告时间大约3-5秒，也可能是我运气比较好？
剧中广告和剧末广告暂时没有发现。

同时测试一下 letv，加载45秒后才能播放，可能是在等待广告时间，只是不显示而已？

**Comment by jc3213** [comment]
乐视有问题吗？能否提供链接供测试？

**Comment by cqhtyi** [comment]
这不清楚了，如果需要等待15秒，那也是很长的时间，
而且没有任何提示，很容易理解为无法播放。

**Comment by jc3213** [comment]
我又重新测试了一下，大概知道问题在哪了，现在加入hardCore以定义Filter的工作模式，0速度更快，1兼容更好（主要是针对sohu和其他可能出现的类似网站）。

**Comment by jc3213** [comment]
@cqhtyi 麻烦再帮忙测试一下吧？

**Comment by kafan15536900** [comment]
根据cancel或者suspend的结果,其实最终触发的是swf里面侦听函数的不同分支,等于是探测黑盒..

**Comment by kafan15536900** [comment]
根据cancel或者suspend的结果,其实最终触发的是swf里面侦听函数的不同分支,等于是探测黑盒..

**Comment by jc3213** [comment]
除了爱奇艺这种把视频跟广告都写在一个脚本里的流氓网站外，其他的都没什么大问题。suspend基本能对付所有国内网站。就是速度问题，这方面cancel速度上更快。至少目前这样能对付这些所有的视频广告了。当然，iqiyi那个方法只是死马当活马医，少看广告不等于完全没广告。

**Comment by kafan15536900** [comment]
suspend等于是暂停 然后等到超时...

**Comment by jc3213** [comment]
这个我倒是能理解，主要还是不太清楚MOZ这边还有什么别的API没有，只是将就着cinhoo的版本改成现在这样罢了。

**Comment by jc3213** [comment]
改了下顺序，第一个f4v 拦截，第一个hml 放行，以后全部拦截，成功实现不看广告。仍需要更多测试来作证现在的做法。

**Comment by kafan15536900** [comment]
总觉得有点像摸鱼..但是却没有太好的办法.

**Comment by jc3213** [comment]
没法子啊，即使把视频换成空内容的，结果是一样的。然后发现commit 2d94dd7f4f0180bf722775eea71d57cbb99f86d2 对iqiyi的播放器的匹配有点问题，并不是次次都能匹配上播放器然后做正确的放行。导致有时候还是会提示兼容问题，这时只需要刷新一下就好了。
